train_file: '/kaggle/working/xray/train_500.json'
test_file: '/kaggle/working/xray/test_500.json'
query_file: '/kaggle/working/xray/test_500.json'
gallery_file: '/kaggle/working/xray/gallery_image_root.json'
train_image_root: '/kaggle/working/xray/train'
test_image_root: '/kaggle/working/xray/test'
gallery_image_root: '/kaggle/working/xray/gallery_image_root'

vit: 'base'
vit_grad_ckpt: False
vit_ckpt_layer: 0
image_size: 224
batch_size_train: 64
batch_size_test: 64

# optimizer
weight_decay: 0.05
init_lr: 3e-4
min_lr: 1e-6
k_test: 10
max_words: 30
window_size: 50

#CL
max_epoch: 30
task: ['Normal', 'Abnormal', 'Uncategorized']
base_mode: 'seqF'

